export const REQUEST_RECIPES = 'REQUEST_RECIPES';
export const RECEIVE_RECIPES = 'RECEIVE_RECIPES';
export const REQUEST_SINGLE_RECIPE = 'REQUEST_SINGLE_RECIPE';
export const RECEIVE_SINGLE_RECIPE = 'RECEIVE_SINGLE_RECIPE';
export const BEGIN_ADD_NEW_RECIPE = 'BEGIN_ADD_NEW_RECIPE';
export const END_ADD_NEW_RECIPE = 'END_ADD_NEW_RECIPE';
export const BEGIN_DELETE_RECIPE = 'BEGIN_DELETE_RECIPE';
export const END_DELETE_RECIPE = 'END_DELETE_RECIPE';